[package]
name = "abdal_http_magnifier"
version = "1.2.1"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
colored = "2.0"
rustyline = "13"